# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f662b3be53d6421ec2dd564a00d3ee19396e16e9f6571badd06bdb2c71e34285d0e24089d827f1e8333a3113d244c81779c9edda2eed2286d9ff0efdd779c6a

test:
  secret_key_base: e6fcdc955630d1568d141030429c421e063a1c1ffcf344b4ff44658a7d3da25824ffdc00f4e69fae3c069fce9101fb87efc77f91f1418e79e6af6cfc8e05266b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
